website:
    resource: "@WebsiteBundle/Controller/"
    type: annotation

about_page:
    path: /about_us
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'WebsiteBundle:Static:about_us.html.twig'

contacts_page:
    path: /contacts
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'WebsiteBundle:Static:contacts.html.twig'